[package]
name = "pyramid-player"
version = "0.1.0"
authors = ["adria0 <adria@codecontext.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.13"